import Link from "next/link";
import { createDnaRecord } from "@/app/(product)/actions";
import { getWorkspaceContext } from "@/lib/studio/workspace";

export const metadata = { title: "Private Universe" };

export default async function UniversePage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const { supabase } = await getWorkspaceContext();
  const { data: records } = await supabase.from("dna_records").select("id, dna_id, dna_type, status, schema_version, version, locked, record, updated_at").order("updated_at", { ascending: false });
  const { error } = await searchParams;
  return <section className="product-page shell"><h1>Continuity has a memory.</h1><p className="lede">Create versioned character, location, and prop DNA once; cast the same identity across productions.</p>{error ? <p className="form-error" role="alert">The DNA record could not be created.</p> : null}<div className="workspace-split"><section className="panel"><h2>Create DNA</h2><form action={createDnaRecord} className="stack-form"><label>Record type<select name="dna_type" defaultValue="CDNA"><option value="CDNA">Character DNA</option><option value="LDNA">Location DNA</option><option value="PDNA">Prop DNA</option></select></label><label>Name<input name="name" maxLength={120} required /></label><label>Continuity summary<textarea name="summary" maxLength={500} rows={3} placeholder="Visual invariants across lighting and scenes." required /></label><label>Visual anchors<input name="anchors" placeholder="Amber coat, scar across jaw, analog watch" maxLength={500} required /></label><label>Voice / behavior<textarea name="voice_behavior" maxLength={500} rows={3} placeholder="Dry, fast cadence, never shouts." /></label><label className="check-row"><input type="checkbox" name="lock_version" />Lock version 1 immediately</label><button className="button button-primary" type="submit">Save DNA</button></form></section><section className="panel"><h2>Continuity registry</h2>{records?.length ? <div className="catalog-list">{records.map((item) => { const body = item.record as { name?: string; summary?: string; anchors?: string[] } | null; return <article className="catalog-row" key={item.id}><div><strong>{body?.name || item.dna_id}</strong><span className="muted"> · {item.dna_type} · v{item.version}</span><p className="muted">{body?.summary || "No summary"}</p>{body?.anchors?.length ? <p className="capability-list">{body.anchors.join(" · ")}</p> : null}</div><div className="catalog-action"><span className={`status-mark ${item.status}`}>{item.status}</span><Link className="button button-outline" href={`/app/universe/${item.id}`}>Manage</Link></div></article>; })}</div> : <p className="muted">No DNA records created yet.</p>}</section></div></section>;
}
