import Link from "next/link";
import { createDnaRecord } from "@/app/(product)/actions";
import { getWorkspaceContext } from "@/lib/studio/workspace";

export const metadata = { title: "Private Universe" };

export default async function UniversePage({ searchParams }: { searchParams: Promise<{ error?: string; tier?: string; group?: string }> }) {
  const { supabase } = await getWorkspaceContext();
  const params = await searchParams;
  let query = supabase.from("dna_records").select("id, dna_id, dna_type, status, schema_version, version, locked, tier, group_type, record, updated_at").order("updated_at", { ascending: false });
  if (params.tier === "A" || params.tier === "B") query = query.eq("tier", params.tier);
  if (["Universe", "Studio", "Channel", "Season", "Socials", "FDNA"].includes(params.group ?? "")) query = query.eq("group_type", params.group);
  const { data: records } = await query;
  const { error } = params;
  return <section className="product-page shell"><h1>Continuity has a memory.</h1><p className="lede">Create versioned DNA once; cast same identity across productions.</p>{error ? <p className="form-error" role="alert">DNA operation failed.</p> : null}<div className="workspace-split"><section className="panel"><h2>Create DNA</h2><form action={createDnaRecord} className="stack-form"><label>Record type<select name="dna_type" defaultValue="CDNA"><option value="CDNA">Character DNA</option><option value="LDNA">Location DNA</option><option value="PDNA">Prop DNA</option></select></label><label>Group<select name="group_type" defaultValue="Universe">{["Universe", "Studio", "Channel", "Season", "Socials", "FDNA"].map((group) => <option key={group}>{group}</option>)}</select></label><label>Name<input name="name" maxLength={120} required /></label><label>Continuity summary<textarea name="summary" maxLength={500} required /></label><label>Visual anchors<input name="anchors" maxLength={500} required /></label><label>Voice / behavior<textarea name="voice_behavior" maxLength={500} /></label><label className="check-row"><input type="checkbox" name="lock_version" />Lock version 1 immediately</label><button className="button button-primary" type="submit">Save DNA</button></form></section><section className="panel"><div className="section-head"><h2>Continuity registry</h2><form className="inline-form"><label>Tier<select name="tier" defaultValue={params.tier ?? ""}><option value="">All</option><option value="A">A</option><option value="B">B</option></select></label><label>Group<select name="group" defaultValue={params.group ?? ""}><option value="">All</option>{["Universe", "Studio", "Channel", "Season", "Socials", "FDNA"].map((group) => <option key={group}>{group}</option>)}</select></label><button className="button button-outline" type="submit">Filter</button></form></div>{records?.length ? <div className="catalog-list">{records.map((item) => { const body = item.record as { name?: string; summary?: string; anchors?: string[] } | null; return <article className="catalog-row" key={item.id}><div><strong>{body?.name || item.dna_id}</strong><span className="muted"> · {item.dna_type} · {item.tier}-tier · {item.group_type}</span><p className="muted">{body?.summary || "No summary"}</p>{body?.anchors?.length ? <p className="capability-list">{body.anchors.join(" · ")}</p> : null}</div><div className="catalog-action"><span className={`status-mark ${item.status}`}>{item.status}</span><Link className="button button-outline" href={`/app/universe/${item.id}`}>Manage</Link></div></article>; })}</div> : <p className="muted">No DNA records match.</p>}</section></div></section>;
}
