import { saveOnboardingStep } from "@/app/(product)/actions";
import { getWorkspaceContext } from "@/lib/studio/workspace";
import { OnboardingAssistant } from "@/components/product/onboarding-assistant";

export const metadata = { title: "Studio setup" };

export default async function OnboardingPage({ searchParams }: { searchParams: Promise<{ step?: string; error?: string }> }) {
  const { supabase } = await getWorkspaceContext();
  const [{ data }, { data: connections }] = await Promise.all([supabase.from("onboarding_profiles").select("mode, step, studio_identity, channel_setup, department_setup").maybeSingle(), supabase.from("provider_connections").select("id, label, provider").eq("status", "active").contains("capabilities", ["text"]).order("label")]);
  const params = await searchParams;
  const step = params.step ?? data?.step ?? "identity";
  const title = step === "identity" ? "Name your studio" : step === "channel" ? "Set up first channel" : step === "hiring" ? "Configure departments" : "Setup complete";
  const guidance = step === "identity" ? "Lanes are teams of agents. Guided mode explains each handoff while you name the studio; Fast mode records choices with fewer prompts." : step === "channel" ? "A channel owns recurring audience context. Season scope can be a film, finite season, or open-ended stream." : "Core departments cover Marketing, Creative, Production, and Social. Add optional teams only when a real workload needs them.";
  return <section className="product-page shell" data-archetype="B1-A"><h1>{title}</h1><p className="lede">Studio assistant setup. Choose guided or fast mode; each step saves server-side.</p><aside className="panel"><strong>Lane guide</strong><p className="muted">{guidance}</p></aside>{data?.mode !== "fast" ? <OnboardingAssistant connections={connections ?? []} /> : null}{params.error ? <p className="form-error" role="alert">Setup could not be saved.</p> : null}{step === "complete" ? <p>Studio ready. <a href="/app">Open Front Office</a>.</p> : <form action={saveOnboardingStep} className="stack-form"><input type="hidden" name="step" value={step} /><label>Assistant mode<select name="mode" defaultValue={data?.mode ?? "guided"}><option value="guided">Guided</option><option value="fast">Fast</option></select></label>{step === "identity" ? <><label>Studio name<input name="studio_name" required maxLength={120} /></label><label>Tagline<input name="tagline" maxLength={240} /></label><label>Content type<input name="content_type" required maxLength={120} /></label></> : step === "channel" ? <><label>Channel name<input name="channel_name" required maxLength={120} /></label><label>Format preset<input name="format" required maxLength={120} /></label><label>Season scope<input name="season_scope" maxLength={240} /></label></> : <><label>Core departments<input name="departments" defaultValue="Marketing, Creative, Production, Social" required /></label><label>Optional teams<input name="optional_departments" /></label></>}<input type="hidden" name="payload" value="{}" /><button className="button button-primary" type="submit">Save and continue</button></form>}</section>;
}
