export type DocArticle = {
  slug: string;
  title: string;
  description: string;
  category: string;
  markdown: string;
};

export const docArticles: DocArticle[] = [
  { slug: "studio-pipeline", title: "Studio Pipeline", description: "Run a production through thirteen visible departments.", category: "Build", markdown: `## One moving picture\n\nGem Studio turns a brief into a sequence of deliberate handoffs. Each department receives a typed brief, records its output, and leaves context for the next lane.\n\n### The thirteen lanes\n\nResearch, Marketing, Creative, Story, Storyboard, Script, Screenplay, AI Conversion, Video Production, Launch, Social Posting, Social Management, and Reporting make up one production.\n\n### Choose your run mode\n\n**Manual** pauses at every gate. **Semi-Automatic** pauses where policy requires review. **Automatic** continues through approved lanes while preserving an audit trail.\n\n> Human approval remains the release boundary. Agents can prepare work; owners decide what ships.` },
  { slug: "dna-continuity", title: "DNA Continuity", description: "Keep characters, worlds, and visual rules consistent.", category: "Build", markdown: `## A continuity record for every story\n\nDNA records capture the facts a production must keep stable: character traits, wardrobe, locations, props, palette, camera language, and exclusions.\n\n### Version, then pin\n\nCreate a new version when canon changes. Pin the version used by a production so later generations cannot silently drift. Compare revisions before promoting a record to shared canon.\n\n### Privacy by workspace\n\nDNA belongs to its workspace. Reads and writes are scoped to the active workspace and protected by row-level access rules.` },
  { slug: "genplay-contracts", title: "GenPlay Contracts", description: "Describe shots precisely before generation starts.", category: "Build", markdown: `## A contract between intent and generation\n\nA GenPlay shot contract makes a single shot reproducible. It names the subject, action, framing, lens, movement, lighting, environment, duration, and continuity references.\n\n### Lock the important fields\n\nKeep prompts focused on observable direction. Attach the DNA version and source assets. Define acceptance checks before sending a job to a provider.\n\n### Review generated media\n\nEvery attempt keeps its input contract, provider metadata, and output reference. Approve one result as the shot master; rejected attempts remain available for audit.` },
  { slug: "byok-security", title: "BYOK Security", description: "Connect providers without exposing production keys.", category: "Operate", markdown: `## Your keys, encrypted\n\nBring-your-own-key connections are accepted server-side and encrypted with AES-256-GCM before storage. The browser never receives the plaintext provider secret.\n\n### Provider resolution\n\nAt run time, policy resolves which provider a lane may use. The worker decrypts only for the request, applies caps, and records an audit event without storing the secret.\n\n### Rotate safely\n\nReplace a key from Account when it changes. Revoke the old key with the provider, then run a small test generation before returning to production.` },
  { slug: "agent-system", title: "Agent System", description: "Hire bounded agents with clear capability contracts.", category: "Operate", markdown: `## Agents work inside lanes\n\nAn agent is hired for a department, not given an open-ended workspace. Its configuration declares capabilities, provider access, model limits, and approval requirements.\n\n### Policy before execution\n\nThe server resolves capability, workspace policy, quota, and audit context before a job starts. A stable error explains blocked work; UI components do not infer policy.\n\n### Human control\n\nPause, retry, or approve from the production timeline. Agent output is a draft until an owner crosses the relevant gate.` },
  { slug: "deployment", title: "Deployment", description: "Move from local setup to a production-ready studio.", category: "Operate", markdown: `## Deploy the smallest safe surface\n\nConfigure Supabase, encryption material, provider credentials, and the worker secret in your deployment environment. Keep production keys out of Git and browser configuration.\n\n### Before launch\n\nRun typecheck, lint, unit tests, migration checks, and the security gate. Verify row-level policies against a second workspace.\n\n### Observe and recover\n\nMonitor job execution and credit reservations. Failed work remains inspectable and retryable; release promotion follows staging approval and the project's branch policy.` },
];

export const docsBySlug = Object.fromEntries(docArticles.map((article) => [article.slug, article]));
